In [94]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [95]:
data=pd.read_csv(r"C:\Users\Karthikeyan C\Downloads\CAR DETAILS FROM CAR DEKHO.csv")
data

name  year  selling_price  km_driven fuel  \
0                        Maruti 800 AC  2007          60000      70000    0   
1             Maruti Wagon R LXI Minor  2007         135000      50000    0   
2                 Hyundai Verna 1.6 SX  2012         600000     100000    1   
3               Datsun RediGO T Option  2017         250000      46000    0   
4                Honda Amaze VX i-DTEC  2014         450000     141000    1   
...                                ...   ...            ...        ...  ...   
4335    Hyundai i20 Magna 1.4 CRDi (1)  2014         409999      80000    1   
4336        Hyundai i20 Magna 1.4 CRDi  2014         409999      80000    1   
4337               Maruti 800 AC BSIII  2009         110000      83000    0   
4338  Hyundai Creta 1.6 CRDi SX Option  2016         865000      90000    1   
4339                  Renault KWID RXT  2016         225000      40000    0   

     seller_type transmission         owner  
0     Individual       Manual   First Owner  
1     Individual       Manual   First Owner  
2     Individual       Manual   First Owner  
3     Individual       Manual   First Owner  
4     Individual       Manual  Second Owner  
...          ...          ...           ...  
4335  Individual       Manual  Second Owner  
4336  Individual       Manual  Second Owner  
4337  Individual       Manual  Second Owner  
4338  Individual       Manual   First Owner  
4339  Individual       Manual   First Owner  

[4340 rows x 8 columns]

In [96]:
dataset=data.head(2500)

In [97]:
X=dataset.iloc[:,[2,3]].values
X.shape

(2500, 2)

In [98]:
y=dataset.fuel.values
y


array(['0', '0', '1', ..., '0', '1', '1'], dtype=object)

In [99]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [100]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [101]:
from sklearn.ensemble import RandomForestClassifier
clfr1=RandomForestClassifier(n_estimators=10,criterion='gini',random_state=0)
clfr1.fit(X_train,y_train)

RandomForestClassifier(n_estimators=10, random_state=0)

In [102]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

ypre=clfr1.predict(X_test)# entropy ypre calculation

ypre1=clfr1.predict(X_test)# gini ypre calculation


In [103]:
print('entropy Accuracy Score:')
accuracy_score(y_test,ypre)*100


entropy Accuracy Score:


78.8

In [104]:
print('entropy Accuracy Score:')
accuracy_score(y_test,ypre)*100


entropy Accuracy Score:


78.8

In [105]:
print('entropy - confusion matrix\n--------------------\n')
print(confusion_matrix(y_test,ypre))
print('gini - confusion matrix\n--------------------\n')
print(confusion_matrix(y_test,ypre1))

entropy - confusion matrix
--------------------

[[183  50   1   1]
 [ 43 210   0   4]
 [  2   1   0   0]
 [  4   0   0   1]]
gini - confusion matrix
--------------------

[[183  50   1   1]
 [ 43 210   0   4]
 [  2   1   0   0]
 [  4   0   0   1]]


In [106]:
print('entropy result\n--------------')
print(classification_report(y_test,ypre))
print('gini index result\n----------------------')
print(classification_report(y_test,ypre1))

entropy result
--------------
              precision    recall  f1-score   support

           0       0.79      0.78      0.78       235
           1       0.80      0.82      0.81       257
           2       0.00      0.00      0.00         3
           3       0.17      0.20      0.18         5

    accuracy                           0.79       500
   macro avg       0.44      0.45      0.44       500
weighted avg       0.79      0.79      0.79       500

gini index result
----------------------
              precision    recall  f1-score   support

           0       0.79      0.78      0.78       235
           1       0.80      0.82      0.81       257
           2       0.00      0.00      0.00         3
           3       0.17      0.20      0.18         5

    accuracy                           0.79       500
   macro avg       0.44      0.45      0.44       500
weighted avg       0.79      0.79      0.79       500

